[package]
name = "de8086"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false

[dependencies]
phf = { version = "0.11.1", features = ["std", "macros"] }
