pub mod common;
mod descriptions;
pub use descriptions::{resolve, Description};
pub mod arithmetic;
pub mod control_transfer;
pub mod data_transfer;
pub mod instruction;
pub mod logic;
pub mod mov;
pub mod opcode;
pub mod processor_control;
pub mod push_pop;
pub mod strings;
